### ISSUE TITLE
Problem in Java 11

### ISSUE THREAD

**Issue by laurocesar** [nemo-ufes/ontouml-lightweight-editor#7]
I can't run `oled2.1.0.jar` in java 11:

```
sicstus@sicstus-VirtualBox:~/Downloads$ java -jar oled2.1.0.jar 
Gtk-Message: 09:11:49.844: Failed to load module "canberra-gtk-module"
Exception in thread "AWT-EventQueue-0" java.lang.NoClassDefFoundError: org/jdesktop/swingx/MultiSplitPane
	at br.ufes.inf.nemo.oled.Main$2.run(Main.java:417)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.ClassNotFoundException: org.jdesktop.swingx.MultiSplitPane
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:471)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:588)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 14 more
sicstus@sicstus-VirtualBox:~/Downloads$ java --version
openjdk 11.0.3 2019-04-16
OpenJDK Runtime Environment (build 11.0.3+7-Ubuntu-1ubuntu218.04.1)
OpenJDK 64-Bit Server VM (build 11.0.3+7-Ubuntu-1ubuntu218.04.1, mixed mode, sharing)
```

**Comment by ghost** [comment]
I have a same problem. Any suggestion?

**Comment by wouterbeek** [comment]
Me too, using OpenJDK 13.

**Comment by rafaelgsilveira** [comment]
Hey guys,
I had to downgrade to Java 8 in order to run OLED. I was running Java 10.
Sorry I don't have a more efficient solution.
